### ISSUE TITLE
Is there any way to support DataBinding?

### ISSUE THREAD

**Issue by Goooler** [sergei-lapin/napt#10]
We are migrating from DataBinding to Compose in a large codebase, but still need Kapt to generate stubs for bindings, is there any way to replace Kapt with Napt?

**Comment by sergei-lapin** [comment]
Hi, @Goooler I've [updated](https://github.com/sergei-lapin/napt/commit/52187c8975379acf67e20ec3f6c8f908b7b55fc4) sample so that to check whether napt works with data binding or not, and, as per my experience — it does.

**Comment by Goooler** [comment]
Thanks for your help, I'll try it and give feedback.

**Comment by Goooler** [comment]
Seems no [BR](https://developer.android.com/topic/libraries/data-binding/generated-binding#dynamic_variables) generated, see https://github.com/Goooler/DemoApp/pull/225#issuecomment-1255978440

**Comment by sergei-lapin** [comment]
BR is generated.  
But, it can be referenced only from `Java` code, since there's no `kapt`.  
See [MainActivityComponentBridge](https://github.com/sergei-lapin/napt/blob/main/sample/src/main/java/com/slapin/napt/sample/dagger/MainActivityComponentBridge.java) for reference.  
I'm closing this one.

**Comment by Goooler** [comment]
I've rechecked, in my case, BR classes were generated in all modules but Main where the BR actually be used.

**Comment by sergei-lapin** [comment]
BR is generated if you do it right. 
![Снимок экрана 2022-09-23 в 17 58 17](https://user-images.githubusercontent.com/20017521/191955365-722b29e3-0263-4646-95a3-1f8db8ebfcb9.png)
![Снимок экрана 2022-09-23 в 17 58 50](https://user-images.githubusercontent.com/20017521/191955444-673cb857-675e-44c7-94f9-87d83db97cb0.png)
![Снимок экрана 2022-09-23 в 17 59 05](https://user-images.githubusercontent.com/20017521/191955494-caa02c24-a067-4190-a240-8e1ff82f3d99.png)
<img width="357" alt="Снимок экрана 2022-09-23 в 17 59 14" src="https://user-images.githubusercontent.com/20017521/191955522-5bcb9bda-0c24-4b29-8e8b-db819f1fcb0f.png">

**Comment by Goooler** [comment]
You are right, I should declare BRBridge first, thanks for your patience!
