### ISSUE TITLE
Junit5 @Nested tests not found

### ISSUE THREAD

**Issue by zsweigart** [sergei-lapin/napt#13]
I migrated to `napt` following the instructions in the README and after fixing the Hilt issue https://github.com/sergei-lapin/napt/issues/11 the app runs fine.

However my unit tests fail to compile because the tests in `@Nested` inner classes cannot be accessed

```
internal class TestClass {

  @Nested
  inner class `nested tests` {
    @Test
    fun `actual test`() {
        true
    }
  }
}
```

with an error
```
error: cannot access nested tests
```

Because I'm using Hilt, I do have the test compiler in my build.gradle file for the module but everything else is standard
```
testAnnotationProcessor deps.hilt.androidTestCompiler
```

**Comment by sergei-lapin** [comment]
Hi, @zsweigart! Are you using version 1.17? 
I've added ability of generation of trigger for all source sets (including tests) there.  
You can enable it via 

```
napt {
   additionalSourceSetsForTriggerGeneration.set(listOf("test"))
}
```
Not sure it's related, worth checking though

**Comment by zsweigart** [comment]
Yea I'm using 1.17 - 

Is that closure supposed to be used within the `android` block? I'm getting a `No signature of method:` both in the `android` closure and outside of it

**Comment by zsweigart** [comment]
Ahh I see in the sample. So I was able to get it to sync, but I'm still getting the `error: cannot access nested tests` error

**Comment by zsweigart** [comment]
So, I'm not sure why this worked or changed anything but by changing the `@Nested` class name from
 ```
inner class `nested tests`
```
to 
 ```
inner class NestedTest
```

worked

**Comment by sergei-lapin** [comment]
closing it then
