### ISSUE TITLE
Feature request: option to disable `NaptTrigger` file generation

### ISSUE THREAD

**Issue by ZacSweers** [sergei-lapin/napt#6]
Would you be open to a pull request to allow disabling of napttrigger file generation? I have two reasons in mind:
- I would feel more sure about kotlinc's incremental compilation accounting for these files if they weren't ephemeral. Gradle + ephemeral files as inputs has bitten us in the past quite often.
- Some of our projects already have java files in them anyway, so it's unnecessary in those

**Comment by sergei-lapin** [comment]
Hey @ZacSweers, great idea! I think this PR https://github.com/sergei-lapin/napt/pull/7 resolves the issue
